### ISSUE TITLE
better control of GoogleVisibleMap domain

### ISSUE THREAD

**Issue by raybellwaves** [fmaussion/salem#110]
firstly, thanks for creating this.

I am trying to create a GoogleVisibleMap by following the example here: http://salem.readthedocs.io/en/latest/auto_examples/plot_googlestatic.html#sphx-glr-auto-examples-plot-googlestatic-py

```
from salem import GoogleVisibleMap, Map
import matplotlib.pyplot as plt

mapextent = [-82, -65, 17, 31] # W, E, S, N

g = GoogleVisibleMap(x=[mapextent[0], mapextent[1]], y=[mapextent[2],
                     mapextent[3]])
ggl_img = g.get_vardata()

fig, ax = plt.subplots(1, 1, figsize=(12,8))
sm = Map(g.grid)
sm.set_rgb(ggl_img)
sm.visualize(ax=ax)
plt.tight_layout()
plt.savefig('test.png')
```

which creates:
![screen shot 2018-07-16 at 1 18 09 pm](https://user-images.githubusercontent.com/17162724/42773260-bd05652e-88fa-11e8-93c6-7dbab5fbabb2.png)

The domain created is approximately [-87, -59, 11, 36] # W, E, S, N.

Am I missing some arguments? e.g. `scale` for `GoogleVisibleMap` or `factor` for `Map`?

What are appropriate values for `scale`? https://github.com/fmaussion/salem/blob/430b9c25a8ffb305fe115517d074b15322b6eafb/salem/datasets.py#L557 and `factor`? https://github.com/fmaussion/salem/blob/325024990f7e0f0f4c48633380845bb959ef5f86/salem/graphics.py#L413 

Or is trying to make the image square?

**Comment by fmaussion** [comment]
Thanks for raising this! The documentation could be more informative indeed.

Are you referring to the fact that the google map doesn't fit *exactly* the provided extent? If so, I'm afraid there is no simple solution: it is a limitation of the static google maps API which only has a finite number of [zoom levels](https://developers.google.com/maps/documentation/maps-static/dev-guide#Zoomlevels). ``GoogleVisibleMap`` chooses the highest zoom level *guaranteed* to cover the provided extent.  

The simplest workaround (but requiring trial and error) is to play with the ``size_*`` kwarg:

```python
from salem import GoogleVisibleMap, Map
import matplotlib.pyplot as plt

mapextent = [-82, -65, 17, 31] # W, E, S, N

g = GoogleVisibleMap(x=[mapextent[0], mapextent[1]], y=[mapextent[2], mapextent[3]],
                     scale=2,  # this provides a higher resolution ggl image but takes longer to download
                     size_x=200, size_y=200,  # this makes the map smaller starting from its centre
                    )
ggl_img = g.get_vardata()

fig, ax = plt.subplots(1, 1, figsize=(12,8))
sm = Map(g.grid, factor=1)  # factor=1 is nicer here because it prevents image resizing
sm.set_rgb(ggl_img)
sm.visualize(ax=ax)
```

Another possibility would be to add an "``ExactGoogleVisibleMap``" which would do this size_* picking for us. I can consider adding this to salem, but it might not be trivial.
