### ISSUE TITLE
salem xarray accessor does not work with latest xarray (xarray==0.11)

### ISSUE THREAD

**Issue by jetesdal** [fmaussion/salem#127]
When running the example (as described here: https://salem.readthedocs.io/en/latest/xarray_acc.html), I get following error. 

import numpy as np
import xarray as xr
import salem

da = xr.DataArray(np.arange(20).reshape(4, 5), dims=['lat', 'lon'],
                  coords={'lat':np.linspace(0, 30, 4),
                          'lon':np.linspace(-20, 20, 5)})
da.salem  # the accessor is an object

AttributeError                            Traceback (most recent call last)
<ipython-input-2-6dad0998c089> in <module>
     6                    coords={'lat':np.linspace(0, 30, 4),
     7                            'lon':np.linspace(-20, 20, 5)})
----> 8 da.salem  # the accessor is an object
     9 
    10 

/usr/local/lib/python3.6/dist-packages/xarray/core/common.py in __getattr__(self, name)
   179                     return source[name]
   180         raise AttributeError("%r object has no attribute %r" %
--> 181                              (type(self).__name__, name))
   182 
   183     def __setattr__(self, name, value):

AttributeError: 'DataArray' object has no attribute ‘salem'

**Comment by fmaussion** [comment]
OK this should work now - you'll have to install from latest master to get the update:

```
pip install git+https://github.com/fmaussion/salem.git
```
