### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by SylvainLan** [fmaussion/salem#136]
Hello, 
I started using your library as I'm working with netcdf data. I usually work with virtualenv and install all needed packages through `pip`. 

I wanted to use `salem` this way too, the install went perfectly but when I wanted to use salem I had errors when trying to turn a xarray dataset into a salem dataset : 
```
AttributeError: 'DataArray' object has no attribute 'salem'
```
or when trying to execute the very first [example](https://salem.readthedocs.io/en/latest/examples.html#subsetting-and-selecting-data) 
```
AttributeError: type object 'xr' has no attribute 'open_dataset'
```

I then git cloned your repo and installed it with `python setup.py install` and it works fine then, but I just wanted to voice this issue I had. 

Thanks !

**Comment by fmaussion** [comment]
Thanks! Did you install with `pip install salem`, i.e. not from git? I guess I should do a new release on PyPi soon, because recent xarray updates are not compatible with the latest stable version from salem

**Comment by SylvainLan** [comment]
Yes that's exactly what I did on the first try

**Comment by fmaussion** [comment]
I released a new release on PyPi a couple of days ago. Thanks for the report!
