### ISSUE TITLE
salem import error with xarray 0.12.0: cannot import name 'basestring'

### ISSUE THREAD

**Issue by nicolasfauchereau** [fmaussion/salem#144]
Hi @fmaussion

Just letting you know that the latest update of xarray (15 March, version 0.12.0) leads to a salem import error in the salem **sio.py** subpackage on line 20:

```
 ---> 20 from xarray.core.pycompat import basestring

ImportError: cannot import name 'basestring'
```

It seems that `basestring` disappeared from `xarray.core.pycompat` between version 0.11.3 and version 0.12.0, although it is not documented on the xarray doc ("what's new")  

Also taking the opportunity to thank you for your amazing work with salem, it's an incredibly useful library ... 

Nico

**Comment by nicolasfauchereau** [comment]
Sorry just seeing this issue has been fixed in master ... apologies for this

**Comment by fmaussion** [comment]
Thanks @nicolasfauchereau ! Will try to pin a new version soon

**Comment by xigrug** [comment]
The salem 0.2.3  this error is existed, how to update?

**Comment by fmaussion** [comment]
> how to update?

you could always install from pip+master, but I just released a version 0.2.4 on pypi which should hopefully work

**Comment by LSgeo** [comment]
Just chucking it out there that conda didn't install salem 0.3 for me first try, and I had to manually specify the update with  `conda install -c oggm salem=0.3`. The issue didn't persist on a clean environment, so it was just local to my environment - but maybe it will help someone in the future.

**Comment by fmaussion** [comment]
Thanks for the hint. We do not maintain a conda-forge package for salem yet, but as you found out @TimoRoth is maintaining a special conda channel. @TimoRoth , do you think we should add this to the installation instructions? https://salem.readthedocs.io/en/stable/installing.html

**Comment by TimoRoth** [comment]
The package on the oggm channel is updated from master whenever I notice it being behind pretty much.
So it's by no means a guarantee to get the latest version.
I think sticking to installing master from git via pip is better for the install instructions.

**Comment by fmaussion** [comment]
> I think sticking to installing master from git via pip is better for the install instructions.

Thanks! I agree
