### ISSUE TITLE
'Dataset' object has no attribute 'salem'

### ISSUE THREAD

**Issue by xigrug** [fmaussion/salem#145]
'Dataset' object has no attribute 'salem'

dataFile = 'wrfout_d01_2019-03-2?_00:00:00'
ds = xr.open_mfdataset(dataFile)

ds
> <xarray.Dataset>
> Dimensions:                (Time: 216, bottom_top: 23, bottom_top_stag: 24, soil_layers_stag: 4, south_north: 74, south_north_stag: 75, west_east: 87, west_east_stag: 88)
> Coordinates:
>     XLAT                   (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     XLONG                  (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     XTIME                  (Time) datetime64[ns] dask.array<shape=(216,), chunksize=(24,)>
>     XLAT_U                 (Time, south_north, west_east_stag) float32 dask.array<shape=(216, 74, 88), chunksize=(24, 74, 88)>
>     XLONG_U                (Time, south_north, west_east_stag) float32 dask.array<shape=(216, 74, 88), chunksize=(24, 74, 88)>
>     XLAT_V                 (Time, south_north_stag, west_east) float32 dask.array<shape=(216, 75, 87), chunksize=(24, 75, 87)>
>     XLONG_V                (Time, south_north_stag, west_east) float32 dask.array<shape=(216, 75, 87), chunksize=(24, 75, 87)>
> Dimensions without coordinates: Time, bottom_top, bottom_top_stag, soil_layers_stag, south_north, south_north_stag, west_east, west_east_stag
> Data variables:
>     Times                  (Time) |S19 dask.array<shape=(216,), chunksize=(24,)>
>     LU_INDEX               (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     ZNU                    (Time, bottom_top) float32 dask.array<shape=(216, 23), chunksize=(24, 23)>
>     ZNW                    (Time, bottom_top_stag) float32 dask.array<shape=(216, 24), chunksize=(24, 24)>
>     ZS                     (Time, soil_layers_stag) float32 dask.array<shape=(216, 4), chunksize=(24, 4)>
>     DZS                    (Time, soil_layers_stag) float32 dask.array<shape=(216, 4), chunksize=(24, 4)>
>     VAR_SSO                (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     U                      (Time, bottom_top, south_north, west_east_stag) float32 dask.array<shape=(216, 23, 74, 88), chunksize=(24, 23, 74, 88)>
>     V                      (Time, bottom_top, south_north_stag, west_east) float32 dask.array<shape=(216, 23, 75, 87), chunksize=(24, 23, 75, 87)>
>     W                      (Time, bottom_top_stag, south_north, west_east) float32 dask.array<shape=(216, 24, 74, 87), chunksize=(24, 24, 74, 87)>
>     PH                     (Time, bottom_top_stag, south_north, west_east) float32 dask.array<shape=(216, 24, 74, 87), chunksize=(24, 24, 74, 87)>
>     PHB                    (Time, bottom_top_stag, south_north, west_east) float32 dask.array<shape=(216, 24, 74, 87), chunksize=(24, 24, 74, 87)>
>     T                      (Time, bottom_top, south_north, west_east) float32 dask.array<shape=(216, 23, 74, 87), chunksize=(24, 23, 74, 87)>
>     HFX_FORCE              (Time) float32 dask.array<shape=(216,), chunksize=(24,)>
>     LH_FORCE               (Time) float32 dask.array<shape=(216,), chunksize=(24,)>
>     TSK_FORCE              (Time) float32 dask.array<shape=(216,), chunksize=(24,)>
>     HFX_FORCE_TEND         (Time) float32 dask.array<shape=(216,), chunksize=(24,)>
>     LH_FORCE_TEND          (Time) float32 dask.array<shape=(216,), chunksize=(24,)>
>     TSK_FORCE_TEND         (Time) float32 dask.array<shape=(216,), chunksize=(24,)>
>     MU                     (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     MUB                    (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     NEST_POS               (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     P                      (Time, bottom_top, south_north, west_east) float32 dask.array<shape=(216, 23, 74, 87), chunksize=(24, 23, 74, 87)>
>     PB                     (Time, bottom_top, south_north, west_east) float32 dask.array<shape=(216, 23, 74, 87), chunksize=(24, 23, 74, 87)>
>     FNM                    (Time, bottom_top) float32 dask.array<shape=(216, 23), chunksize=(24, 23)>
>     FNP                    (Time, bottom_top) float32 dask.array<shape=(216, 23), chunksize=(24, 23)>
>     RDNW                   (Time, bottom_top) float32 dask.array<shape=(216, 23), chunksize=(24, 23)>
>     RDN                    (Time, bottom_top) float32 dask.array<shape=(216, 23), chunksize=(24, 23)>
>     DNW                    (Time, bottom_top) float32 dask.array<shape=(216, 23), chunksize=(24, 23)>
>     DN                     (Time, bottom_top) float32 dask.array<shape=(216, 23), chunksize=(24, 23)>
>     CFN                    (Time) float32 dask.array<shape=(216,), chunksize=(24,)>
>     CFN1                   (Time) float32 dask.array<shape=(216,), chunksize=(24,)>
>     THIS_IS_AN_IDEAL_RUN   (Time) int32 dask.array<shape=(216,), chunksize=(24,)>
>     P_HYD                  (Time, bottom_top, south_north, west_east) float32 dask.array<shape=(216, 23, 74, 87), chunksize=(24, 23, 74, 87)>
>     Q2                     (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     T2                     (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     TH2                    (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     PSFC                   (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     U10                    (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>
>     V10                    (Time, south_north, west_east) float32 dask.array<shape=(216, 74, 87), chunksize=(24, 74, 87)>

u_1= ds.isel(Time=1)

> <xarray.Dataset>
> Dimensions:                (bottom_top: 23, bottom_top_stag: 24, soil_layers_stag: 4, south_north: 74, south_north_stag: 75, west_east: 87, west_east_stag: 88)
> Coordinates:
>     XLAT                   (south_north, west_east) float32 dask.array<shape=(74, 87), chunksize=(74, 87)>
>     XLONG                  (south_north, west_east) float32 dask.array<shape=(74, 87), chunksize=(74, 87)>
>     XTIME                  datetime64[ns] dask.array<shape=(), chunksize=()>
>     XLAT_U                 (south_north, west_east_stag) float32 dask.array<shape=(74, 88), chunksize=(74, 88)>
>     XLONG_U                (south_north, west_east_stag) float32 dask.array<shape=(74, 88), chunksize=(74, 88)>
>     XLAT_V                 (south_north_stag, west_east) float32 dask.array<shape=(75, 87), chunksize=(75, 87)>
>     XLONG_V                (south_north_stag, west_east) float32 dask.array<shape=(75, 87), chunksize=(75, 87)>
> Dimensions without coordinates: bottom_top, bottom_top_stag, soil_layers_stag, south_north, south_north_stag, west_east, west_east_stag
> Data variables:
>     Times                  |S19 dask.array<shape=(), chunksize=()>

u_1.salem.wrf_zlevel('U', levels=10000.)
**AttributeError:  'Dataset' object has no attribute 'salem'**

**Comment by fmaussion** [comment]
Probably related to https://github.com/fmaussion/salem/issues/144 , right? Feel free to re-open if updating didn't solve your problem.
