### ISSUE TITLE
download salem-sample-data to .salem_cache failed 

### ISSUE THREAD

**Issue by guoanby** [fmaussion/salem#181]
download salem-sample-data to .salem_cache failed. Can you give me the link where I can download the sample by myself?

**Comment by fmaussion** [comment]
Hi, I never heard of any problem with that. Check your internet connection, delete the salem cache (https://salem.readthedocs.io/en/stable/faq.html#what-s-this-salem-cache-directory-in-my-home-folder) and try again!

**Comment by cuitwhf** [comment]
I have also meet this problem.

**Comment by cuitwhf** [comment]
And i sure that my Internet connection worked well.
