### ISSUE TITLE
value error when trying to subset netcdf file

### ISSUE THREAD

**Issue by lwasser** [fmaussion/salem#185]
Hi there 👋 @fmaussion 

i wondered if you could have a look at my code to help me understand how salem works with subsetting. 
i'm interested in generating spatial masks to perform computation on subsets of netcdf4 climate data files.

However when i do that i am getting a value error.
I wondered if it *could* have to do with the netcdf data being in that funky global CRS that runs from 0-360 for longitude values rather than typical epsg 4326 which has positive and negative values. Do you have any thoughts on what may be happening below? perhaps i'm just doing something wrong? thank you for your time. i want too start teaching netcdf  and will publish the lessons on our learning portal if i can figure out the right approach that works! 

```
import salem
# this is the shapefile https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_1_states_provinces_lakes.zip 
# i'm using as a boundary 
# Read with salem / geopandas? 
cali_bound = salem.read_shapefile(states_path)
cali_bound = shdf.loc[shdf['name'].isin(['California'])]
# Open file as xarray object
temp = salem.open_xr_dataset('http://thredds.northwestknowledge.net:8080/thredds/dodsC/agg_macav2metdata_tasmax_BNU-ESM_r1i1p1_rcp45_2006_2099_CONUS_monthly.nc')
# Do i need to reproject or something? the data come in above in lat / lon epsg 4326 whereas the data 
# in the netcdf file are that weird global crs with 0-360 long values
t2_sub = temp.salem.subset(shape=shdf, margin=2)  # add 2 grid points
```

returns
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-1eabc1213c34> in <module>
----> 1 t2_sub = temp.salem.subset(shape=shdf, margin=2)  # add 2 grid points

~/opt/miniconda3/envs/earth-analytics-python/lib/python3.8/site-packages/salem/sio.py in subset(self, margin, ds, **kwargs)
    469 
    470         ids = np.nonzero(mask)
--> 471         sub_x = [np.min(ids[1]) - margin, np.max(ids[1]) + margin]
    472         sub_y = [np.min(ids[0]) - margin, np.max(ids[0]) + margin]
    473 

<__array_function__ internals> in amin(*args, **kwargs)

~/opt/miniconda3/envs/earth-analytics-python/lib/python3.8/site-packages/numpy/core/fromnumeric.py in amin(a, axis, out, keepdims, initial, where)
   2828     6
   2829     """
-> 2830     return _wrapreduction(a, np.minimum, 'min', axis, None, out,
   2831                           keepdims=keepdims, initial=initial, where=where)
   2832 

~/opt/miniconda3/envs/earth-analytics-python/lib/python3.8/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85                 return reduction(axis=axis, out=out, **passkwargs)
     86 
---> 87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     88 
     89 

ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by fmaussion** [comment]
Hi @lwasser - thanks for the nicely summarized issue.

Yes you have guessed right, the 0-360 lon array was the issue. Here is something that works: https://gist.github.com/fmaussion/2bb71b975b14be74cb4e77804401dcf1 

(related: https://github.com/fmaussion/salem/issues/73)

I'm a bit sad to say that but I won't recommend to use salem for teaching - the project is a bit stalled and the kind of basic issue you encountered is a bit unfortunate. Did you try @mathause 's regionmask as well? https://github.com/mathause/regionmask

**Comment by lwasser** [comment]
hi @fmaussion thank you for the quick reply and for the input on this package! it's very helpful. I am playing with @mathause 's regionmask now too and have gotten it to work thanks so some input from him as well.

If this project is stalled then I will just focus on regionmask! I was trying to decide which package to teach so this input much appreciated!!
