### ISSUE TITLE
Something wrong with version number in source distribution

### ISSUE THREAD

**Issue by thebaptiste** [fmaussion/salem#187]
When installing source distribution of salem 0.3.0 (`pip install --no-binary salem salem==0.3.0`) I had this message : 

` WARNING: Requested salem==0.3.0 from https://files.pythonhosted.org/packages/0b/21/52412bea7cc152f46003f57b1164e3e8bef36de09ec23d41f543f146f6ad/salem-0.3.0.tar.gz#sha256=a592aee17fd23e5c80f37386cdd80da62163a0f1d9f1de01abe6dd86863f6bfc, but installing version 0.2.2.dev0`
`Successfully installed salem-0.2.2.dev0`

That is not the case with salem 0.2.4

Could you do something ?

Thanks

**Comment by fmaussion** [comment]
What happens if you install salem only once?

`pip install --no-binary salem==0.3.0`

(without the two salems)

**Comment by thebaptiste** [comment]
I install it only once. You have to provide a package name for each --no-binary option and a list of package to install.
Example : `pip install --no-binary package1 --no-binary package2 package1 package2 package 3` means that package1 and package2 will be installed with source distribution and package3 with binary distribution

**Comment by thebaptiste** [comment]
And `pip install --no-binary salem==0.3.0` fails : 
`ERROR: You must give at least one requirement to install (see "pip help install")`

**Comment by fmaussion** [comment]
To be honest I don't know how to solve that. `pip install salem==0.3.0` works fine.

What are you trying to achieve with `--no-binary`?  salem is a pure python package, do you know what I should do to change this behavior?

**Comment by fmaussion** [comment]
Ah maybe something with setup.py : https://github.com/fmaussion/salem/blob/master/setup.py

**Comment by fmaussion** [comment]
I thought I had some automated versioning in place here but apparently not...

**Comment by thebaptiste** [comment]
Yes, there is probably something wrong in your setup.py

I work on a project where we have to install many python packages. Among them some are depending on C-libraries we are also providing. In some corny cases, installing python packages from source distribution rather than binary may resolve some problems between python and C libraries (see for example [here](https://www.psycopg.org/articles/2018/02/08/psycopg-274-released/) So we prefer to install all python packages from source distribution.

**Comment by thebaptiste** [comment]
One of our users has recently asked for us to add salem in the packages we provide. That's the reason of this issue.

**Comment by thebaptiste** [comment]
May be in setup.py you just have to change MINOR and MICRO, set ISRELEASED to True, publish the release and set back ISRELEASED to False ?
If you want, if you build a new source tarball, l I can test it before you release on pypi (because there is no way to revert on pypi) ?

**Comment by fmaussion** [comment]
OK should be solved in 0.3.1: https://pypi.org/project/salem/#history

**Comment by thebaptiste** [comment]
It works.
Thank you very much for your reactivity.

Regards

**Comment by fmaussion** [comment]
I did all this and inadvertently created a bad bug in the version uploaded to pypi: https://github.com/fmaussion/salem/pull/188

I'll have to release 0.3.2 asap, I'll let you know when this is done

**Comment by thebaptiste** [comment]
Ok. I wait for your new release. Let me know.

**Comment by fmaussion** [comment]
@thebaptiste 

I'm really tired but I think that 0.3.3 is now correct and working: https://pypi.org/project/salem/#history

**Please tag 0.3.3** as 0.3.1 is badly flawed and 0.3.2 was badly released...

**Comment by thebaptiste** [comment]
Thank you very much @fmaussion but I was not in such a hurry, it could have waited tomorrow or later...
Have a good rest and many thanks again !

**Comment by fmaussion** [comment]
Yes I know, but I was uncomfortable knowing that a release on PyPi had such a flaw... :see_no_evil:
