### ISSUE TITLE
Question: Total precipitation PRCP.

### ISSUE THREAD

**Issue by camilomarquez** [fmaussion/salem#193]
Hello,
I don't have a problem, it's a question, how is PRCP calculated?
My question is the same one that maybe you asked years ago (https://forum.wrfforum.com/viewtopic.php?f=37&t=1199)

When I calculate the total precipitation making a sum of all PRCPs during all the time steps occupying sum, I obtain very high values, about 25000 mm in a glacier of mid latitudes in Chile.

When I calculate rainc + rainnc I get about 12000 mm.

Maybe I'm doing something wrong, so I would like to know how the PRCP variable is calculated please.

ds=salem.open_wrf_dataset(list_of_paths[1])
ds_pp=ds.PRCP.sum('time', keep_attrs=True)

for ii in range(2,len(list_of_paths)):
    ds=salem.open_wrf_dataset(list_of_paths[ii])
    ds_pp_i=ds.PRCP.sum('time', keep_attrs=True)
    ds_pp.values=ds_pp.values+ds_pp_i.values 

ds_pp.salem.quick_map(cmap='RdBu')

Thank you very much for sharing this valuable work,
Cheers

**Comment by fmaussion** [comment]
PRCP in salem de-accumulates the flux variables (i.e. units of mm per hour) and then adds RAINC and RAINNC together.

ds.PRCP.sum() might or might not work depending on the timestep, units is allways mm per hour as stated in the units of the DataArray.

**Comment by camilomarquez** [comment]
Thanks for the quick reply Fabien. So I am wrong, I have data every half hour.
