### ISSUE TITLE
salem.subset and salem.roi wrong result

### ISSUE THREAD

**Issue by Jing25** [fmaussion/salem#200]
The salem.subset and salem.roi don't seem work properly.

```
out_mask = nc.salem.subset(shape=shp)

fig, ax = plt.subplots(figsize=(8, 8))
ax.imshow(out_mask, extent=extent)
shp.plot(ax=ax)
```

Here's what I got:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/27107288/116352184-a1280c00-a7a9-11eb-9097-4be5329e4146.png">

Looks like the cropped area is to the bottom left of the shape that I have. This is not correct. I'm wondering if this is a bug?

**Comment by fmaussion** [comment]
Hi, you don't provide enough information / data for me to reproduce the problem. Please have a look at http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports about how to write a good bug report.

That being said, I see potential issues in your example:

```python
ax.imshow(out_mask, extent=extent)
```
what is `extent` here? when you subset data, the extent of the map changes. Furthermore, one of the main points of salem is to use salem for plotting maps as well, this avoids issues like this one.

```
out_mask = nc.salem.subset(shape=shp)
```

Why aren't you using the xarray salem decorator instead? Note also that `subset` "cuts" the dataset, maybe you are also looking for `roi`?

**Comment by Jing25** [comment]
`extent = nc.salem.grid.extent`

For the shape I mention here, any polygon would work, for example:
```
gbox = geometry.box(*[-121, 34, -120, 35])
shp = gpd.GeoSeries(geometry.Polygon(gbox))
subset = nc.salem.subset(geometry=gbox)
```
Here's another test with this simple box:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/27107288/116484172-5eb00f00-a83d-11eb-896f-ab82e28f4ef1.png">

You can still see the slightly shift.

`nc` is an xarray dataarray with 30 m spatial resolution. My observation is that, salem.subset or salem.roi works find when target image resolution is not very high, like 1 km. But for high resolution images, it will have some problems, such as memory consuming and incorrect result as is shown here.

**Comment by fmaussion** [comment]
still, I can't help you if I can't reproduce the problem, sorry!

**Comment by Jing25** [comment]
Thank you anyway. I cannot reproduce the problem with a small sample raster data either. Salem may have some inconsistency when process high-res large data but it could be my problem.
