### ISSUE TITLE
Incorrect grid inference with irregular latitude spacing

### ISSUE THREAD

**Issue by darothen** [fmaussion/salem#49]
I've been playing with salem for analyzing some GEOS-Chem output which I've inherited from a previous post-doc. One of the first things I've been doing is extracting data from parts of the USA using shapefiles from Natural Earth. But I think I've stumbled across a small bug that I want to highlight for you.

For starters, [here's a sample 2D lat-lon dataset](https://www.dropbox.com/s/0l9y9dfwb5ppz59/test.nc?dl=0). We load it up like normal, using xarray and salem:

``` python
import xarray as xr
import salem

data = xr.open_dataset("test.nc")
```

There's an issue with the latitudes in this dataset. The last and first gridpoints are just 1.5 degrees away from the points separating them, while the rest of the grid is equally spaced at 2 degrees. If I try to use "quick_map" on this dataset, I get this:

![image](https://cloud.githubusercontent.com/assets/4992424/21697671/75428d02-d361-11e6-8161-0f73b37145bd.png)

It's clipped at just over 40N. Luckily, the shapefile subsetting functions still work okay, in principle, but there's a big problem:

``` python
shdf = salem.read_shapefile(salem.get_demo_file('world_borders.shp'))
roi = ozone.salem.roi(shape=shdf)
roi.salem.quick_map()
```

![image](https://cloud.githubusercontent.com/assets/4992424/21697858/5cd00c08-d362-11e6-9463-a9e95c14e7e7.png)

This map looks *okay*, but the data is geo-referenced incorrectly; basically, salem has tried to stretch the latitudes 90S to 42N to cover our entire map, even though it stretches from 90S to 90N.

However, if we clip off those problematic first and last latitude points, things work much better:

``` python
ozone_subset = ozone.isel(lat=slice(1, -1))
ozone_subset.salem.quick_map()
```

![image](https://cloud.githubusercontent.com/assets/4992424/21697841/47f97404-d362-11e6-9946-8bad36e371f8.png)

And the subsetted data looks much better, too

![image](https://cloud.githubusercontent.com/assets/4992424/21697918/a9f2379a-d362-11e6-8d9f-fec1527d76bc.png)

---

Any ideas on what might be the cause of this? I'm not sure if there's a special, custom grid projection I could've passed to salem to help it figure things out in this case. Luckily, cutting off the problematic latitudes is fine - and I'm not looking at the poles in my current studies.

**Comment by fmaussion** [comment]
Thanks a lot for the report! 

Salem is not supposed to work with irregular coordinates or without a proper map projection (I should make it clear in the documentation).

But I'll still have a closer look at your file tomorrow morning (it's getting late here in Innsbruck)

**Comment by fmaussion** [comment]
In fact, your coordinates are regular, but it's the bounds which are strange: 

```
lat = -89.5, -88, -86, -84, -82, -80, -78, -76, -74, -72, -70, -68, -66, 
    -64, -62, -60, -58, -56, -54, -52, -50, -48, -46, -44, -42, -40, -38, 
    -36, -34, -32, -30, -28, -26, -24, -22, -20, -18, -16, -14, -12, -10, -8, 
    -6, -4, -2, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 
    32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 
    68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 89.5 ;
```

This is quite unconventional. I'll look at it more closely soon!

**Comment by fmaussion** [comment]
So the problem happens [here](https://github.com/fmaussion/salem/blob/master/salem/sio.py#L258-L260). Beccause of the smaller grid spacings at the poles, Salem thought the grid spacing was 1.5 instead of 2, which explains the strange map going up to 40°N that you obtained. 

Salem is not supposed to work with irregular grids, so I should add a test to warn users when there are dubious coordinates. In your case, I think it's safe to consider it regular and simply correct the coordinates at the pole:

```python
import salem
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

ds = xr.open_dataset('test.nc')
# correct the poles
lat = ds.lat.values
lat[[0, -1]] = [-90, 90]
ds['lat'] = lat

shdf = salem.read_shapefile(salem.get_demo_file('world_borders.shp'))
roi = ds.salem.roi(shape=shdf)

ax = plt.axes(projection=ccrs.Robinson())
roi.IJ_AVG_S__O3.plot.imshow(ax=ax, transform=ds.salem.cartopy())
ax.coastlines();
plt.show()
```
![untitled](https://cloud.githubusercontent.com/assets/10050469/21713031/1ecb4c56-d3f8-11e6-96c2-632242d4a7bc.png)

A couple of remarks:
- for global plots I'd recommend to use cartopy (salem.Maps are for regional applications)
- the same holds true for the ROI generation: the high resolution country borders used by salem are a bit "too much" in comparison to your coarse dataset. We could use either the coastlines shapefile provided by cartopy, or - even better - add a medium to low-res shapefile to salem's sample dataset (would be useful for your case!)

**Comment by darothen** [comment]
Hi Fabian, 

Thanks for the diagnosis. I do use cartopy maps in my production plots, just wanted to "quick show" you some things :). Because there's a heavy cartopy preference, I do not think you need to invest in including other shapefiles by default in salem; just lean on [cartopy's Natural Earth integration](http://scitools.org.uk/cartopy/docs/v0.13/matplotlib/feature_interface.html#cartopy.feature.NaturalEarthFeature). In fact, in my production version of the plots I showed you, I'm using their US states/territories shapefiles to do my ROI calculation. 

Good to know about the need for regular grids. Like you noticed, it's trivial enough to tweak the GEOS-Chem output to handle that situation. I'll close this issue since we know it's not a bug.
