### ISSUE TITLE
Setting colorbar range in salem

### ISSUE THREAD

**Issue by ritviksahajpal** [fmaussion/salem#80]
Is there a way to specify a colorbar in salem which truncates beyond a certain number. It is possible to do it in matplotlib like this:

```
cs.set_over('k')
cs.set_clim(0, 200)
```

**Comment by fmaussion** [comment]
If I understand you question correctly, yes. Salem's ``DataLevels`` class (from which ``Map`` inherits) was created to take care of this. The colorbar is extended automatically if the max level is chosen below the max data point:

```python
import salem
import numpy as np
import matplotlib.pyplot as plt

a = np.arange(9).reshape((3, 3))

dl = salem.DataLevels(a)
dl.set_plot_params(levels=[2, 3, 4, 5])
dl.visualize()
```
gives:

![index](https://cloud.githubusercontent.com/assets/10050469/26286825/7cd0baf8-3e6e-11e7-8014-86a1ed50841a.png)

If you want to give those another color then you have to set it on the colormap first:

```python
cmap = plt.get_cmap('viridis')
cmap.set_over('k')
dl.set_plot_params(levels=[2, 3, 4, 5], cmap=cmap)
dl.visualize()
```
gives:

![index2](https://cloud.githubusercontent.com/assets/10050469/26286835/a584d09c-3e6e-11e7-8f60-26fba1c525fd.png)

**Comment by fmaussion** [comment]
If you are talking about "clipping" you data, then no: salem doesn't clip your data (by design, because I think that the plot function should not hide infos to the user). Trying to overide this results in a warning:

```python
dl.set_plot_params(levels=[2, 3, 4, 5], cmap=cmap, extend='neither')
dl.visualize()
```

throws:

```
/home/mowglie/Documents/git/salem/salem/graphics.py:270: RuntimeWarning: Minimum data out of bounds.
  warnings.warn('Minimum data out of bounds.', RuntimeWarning)
/home/mowglie/Documents/git/salem/salem/graphics.py:272: RuntimeWarning: Maximum data out of bounds.
  warnings.warn('Maximum data out of bounds.', RuntimeWarning)
```

**Comment by ritviksahajpal** [comment]
Thanks again @fmaussion , your solutions are both great!
